import types
from System.Windows.Forms import Form
from _typeshed import Incomplete

informats: Incomplete
outformats: Incomplete
descs: Incomplete
fps: Incomplete
forcefields: Incomplete
charges: Incomplete
operations: Incomplete
ipython_3d: bool

def readfile(format, filename, opt=None): ...
def readstring(format, string, opt=None): ...

class Outputfile:
    format: Incomplete
    filename: Incomplete
    obConversion: Incomplete
    total: int
    def __init__(self, format, filename, overwrite: bool = False, opt=None) -> None: ...
    def write(self, molecule) -> None: ...
    def close(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

class Molecule:
    OBMol: Incomplete
    def __init__(self, OBMol) -> None: ...
    @property
    def atoms(self) -> int: ...
    @property
    def residues(self): ...
    @property
    def charge(self): ...
    @property
    def conformers(self): ...
    @property
    def data(self): ...
    @property
    def dim(self): ...
    @property
    def energy(self): ...
    @property
    def exactmass(self): ...
    @property
    def formula(self): ...
    @property
    def molwt(self): ...
    @property
    def spin(self): ...
    @property
    def sssr(self): ...
    title: Incomplete
    @property
    def unitcell(self): ...
    @property
    def clone(self): ...
    def __iter__(self): ...
    def calcdesc(self, descnames=[]): ...
    def calcfp(self, fptype: str = 'FP2'): ...
    def calccharges(self, model: str = 'mmff94'): ...
    def write(self, format: str = 'smi', filename=None, overwrite: bool = False, opt=None): ...
    def localopt(self, forcefield: str = 'mmff94', steps: int = 500) -> None: ...
    def make2D(self) -> None: ...
    def make3D(self, forcefield: str = 'mmff94', steps: int = 50) -> None: ...
    def addh(self) -> None: ...
    def removeh(self) -> None: ...
    def convertdbonds(self) -> None: ...
    def draw(self, show: bool = True, filename=None, update: bool = False, usecoords: bool = False) -> None: ...

class Atom:
    OBAtom: Incomplete
    def __init__(self, OBAtom) -> None: ...
    @property
    def coords(self): ...
    @property
    def atomicmass(self): ...
    @property
    def atomicnum(self): ...
    @property
    def cidx(self): ...
    @property
    def coordidx(self): ...
    @property
    def degree(self): ...
    @property
    def exactmass(self): ...
    @property
    def formalcharge(self): ...
    @property
    def heavydegree(self): ...
    @property
    def heavyvalence(self) -> None: ...
    @property
    def heterodegree(self): ...
    @property
    def heterovalence(self) -> None: ...
    @property
    def hyb(self): ...
    @property
    def idx(self): ...
    @property
    def implicitvalence(self): ...
    @property
    def isotope(self): ...
    @property
    def partialcharge(self): ...
    @property
    def residue(self): ...
    @property
    def spin(self): ...
    @property
    def type(self): ...
    @property
    def valence(self) -> None: ...
    @property
    def vector(self): ...

class Residue:
    OBResidue: Incomplete
    def __init__(self, OBResidue) -> None: ...
    @property
    def atoms(self) -> int: ...
    @property
    def idx(self): ...
    @property
    def name(self): ...
    def __iter__(self): ...

class Fingerprint:
    fp: Incomplete
    def __init__(self, fingerprint) -> None: ...
    def __or__(self, other): ...
    @property
    def bits(self): ...

class Smarts:
    obsmarts: Incomplete
    def __init__(self, smartspattern) -> None: ...
    def findall(self, molecule): ...

class MoleculeData:
    def __init__(self, obmol) -> None: ...
    def keys(self): ...
    def values(self): ...
    def items(self): ...
    def __iter__(self): ...
    def iteritems(self): ...
    def __len__(self) -> int: ...
    def __contains__(self, key) -> bool: ...
    def __delitem__(self, key) -> None: ...
    def clear(self) -> None: ...
    def has_key(self, key): ...
    def update(self, dictionary) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...

class _MyForm(Form):
    def __init__(self) -> None: ...
    ClientSize: Incomplete
    Text: Incomplete
    filename: Incomplete
    image: Incomplete
    def setup(self, filename, title) -> None: ...
